<?php
return array(
    'title' => 'Размещение заказа',
    'description' => '',
    'countries' => $countries,
    'deliveryMethods' => $this->delivery(),
    'sign_in' => 'Войдите',
    'info_label' => 'если у вас есть аккаунт',
    'shipping_details' => 'Информация для доставки',
    'email' => 'E-mail',
    'first_name' => 'Имя',
    'last_name' => 'Фамилия',
    'address_1' => 'Адрес 1',
    'address_2' => 'Адрес 2',
    'postal' => 'Индекс',
    'city' => 'Город',
    'phone' => 'Телефон',
    'country_label' => 'Страна',
    'delivery_method' => 'Способ доставки',
    'payment_method' => 'Способ оплаты',
    'summary' => 'Всего к оплате',
    'order' => 'Заказ',
    'delivery' => 'Доставка',
    'total' => 'Итого',
    'proceed' => 'Перейти к оплате',
);