<?php
return array(
    'title' => 'Złożenie zamówienia',
    'description' => '',
    'countries' => $countries,
    'deliveryMethods' => $this->delivery(),
    'sign_in' => 'Załoguj się',
    'info_label' => 'jeźeli masz konto',
    'shipping_details' => 'Szczegóły dostawy',
    'email' => 'E-mail',
    'first_name' => 'Imię',
    'last_name' => 'Nazwisko',
    'address_1' => 'Adres 1',
    'address_2' => 'Adres 2',
    'postal' => 'Kod pocztowy',
    'city' => 'Miasto',
    'phone' => 'Telefon',
    'country_label' => 'Kraj',
    'delivery_method' => 'Sposób dostawy',
    'payment_method' => 'Metoda płatności',
    'summary' => 'Podsumowanie',
    'order' => 'Zamówienie',
    'delivery' => 'Dostawa',
    'total' => 'Razem',
    'proceed' => 'Przejdź do płatności',
);