<?php
return array(
    'footer'=>'This is footer',
    'information' => 'Informacja',
    'about_us' => 'O firmie',
    'delivery_info' => 'Informacja o dostawie',
    'privacy_policy' => 'Polityka prywatnośći',
    'terms_conditions' => 'Zasady i warunki',
    'customer_service' => 'Obsługa klienta',
    'contact_us' => 'Skontaktuj się z nami',
    'returns' => 'Zwroty',
    'sitemap' => 'Sitemap',
    'extras' => 'Dodatkowa informacja',
    'brands' => 'Marki',
    'gift_vouchers' => 'Podarunkowe certyfikaty',
    'affiliates' => 'Program partnerski',
    'specials' => 'Promocje',
    'my_account' => 'Moje konto',
    'order_history' => 'Historia zamówień',
    'wishlist' => 'Lista życzeń',
    'newsletter' => 'Newsletter',
    'powered_by' => 'Powered by',
);