<?php
return array(
    'title' => 'Checkout',
    'description' => '',
    'countries' => $countries,
    'deliveryMethods' => $this->delivery(),
    'sign_in' => 'Sign in',
    'info_label' => 'if you have an account',
    'shipping_details' => 'Shipping details',
    'email' => 'E-mail',
    'first_name' => 'First name',
    'last_name' => 'Last Name',
    'address_1' => 'Address 1',
    'address_2' => 'Address 2',
    'postal' => 'ZIP/Postal',
    'city' => 'City',
    'phone' => 'Phone',
    'country_label' => 'Country',
    'delivery_method' => 'Delivery method',
    'payment_method' => 'Payment method',
    'summary' => 'Summary',
    'order' => 'Order',
    'delivery' => 'Delivery',
    'total' => 'Total',
    'proceed' => 'Proceed to payment',
);